[package]
name = "zip-info"
version = "0.1.4"
authors = ["Don Rowe <rowedonalde@gmail.com>"]

[[bin]]
path = "src/main.rs"
name = "zi"

[dependencies]
docopt = "0.6.86"
glob = "0.2.11"
rustc-serialize = "0.3.19"
zip = "0.1.19"
